import os

DB_PATH = os.environ.get("DB_PATH", "data.db")

MIN_TRANSACTION_AMOUNT = 0.01
MAX_TRANSACTION_AMOUNT = 1_000_000 
MAX_USER_ID_LENGTH = 50
MAX_DESCRIPTION_LENGTH = 200
MAX_IDEMPOTENCY_KEY_LENGTH = 100


RATE_LIMIT_WINDOW_SECONDS = 10
RATE_LIMIT_MAX_REQUESTS = 5

PER_TRANSACTION_SCORE_CAP = 10_000   
AMOUNT_WEIGHT = 1.0
ACTIVITY_WEIGHT = 15.0

DEFAULT_RANKING_PAGE_SIZE = 20
MAX_RANKING_PAGE_SIZE = 100
